### ISSUE TITLE
   dataset  of "SBEM, TEM Membranes (50789)"

### ISSUE THREAD

**Issue by xinsheng44** [CRBS/cdeep3m2#24]
Hi there,

I hope you're doing well. I've been using your project and I'm quite impressed with its features. However, I encountered an issue while trying to segment my mitochondria data with "SBEM, TEM Membranes (50789)".

I am currently trying to train a proprietary domain segmentation model, and I have found that "SBEM, TEM Membranes (50789)" works very well for my sample data segmentation. 

Since my labeled dataset is little, I would like to request  dataset of "SBEM, TEM Membranes (50789)" . Can you make your training dataset publicly available?

I understand that you all are busy, but if you could spare some time to look into this, it would be greatly appreciated. Thank you so much for your hard work on this project!

Best regards,
xinsheng

**Comment by haberlmatt** [comment]
Hi,
if you are trying to segment Mitochondria, you can use this model:
https://doi.org/10.7295/W9CDEEP3M50689 
SBEM Mitochondria (denoised)

**Comment by xinsheng44** [comment]
> Hi, if you are trying to segment Mitochondria, you can use this model: https://doi.org/10.7295/W9CDEEP3M50689 SBEM Mitochondria (denoised)

Thank you for your reply.

I test most of the models on the Cdeep3M website and found that “https://doi.org/10.7295/W9CDEEP3M50789” is a better fit for my data because my data is 2D. 

Here are the results of my tests.

https://doi.org/10.7295/W9CDEEP3M50789
![image](https://github.com/CRBS/cdeep3m2/assets/59272013/1ccba3d0-a4c8-411b-8f9a-c00c3565e030)

https://doi.org/10.7295/W9CDEEP3M50689
![image](https://github.com/CRBS/cdeep3m2/assets/59272013/1146f47f-6db7-462d-bf0f-0e43172609c4)

But the effect is not as expected, so I want to get “https://doi.org/10.7295/W9CDEEP3M50789”  corresponding training dataset.

So, could you open source the relevant data set for the corresponding model “https://doi.org/10.7295/W9CDEEP3M50789”?

Thanks!
